Entities/Answer.cs
namespace MillionaireWeb.Entities;

public class Answer
{
    public int Id { get; set; }
    public int QuestionId { get; set; }
    public string Content { get; set; }
    public bool IsCorrect { get; set; } = false;

    public virtual Question Question { get; set; }
}

Entities/GameDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace MillionaireWeb.Entities;

public class GameDbContext : DbContext
{
    public GameDbContext(DbContextOptions<GameDbContext> options)
        : base(options)
    {
    }

    public DbSet<Question> Questions { get; set; }
    public DbSet<Answer> Answers { get; set; }
    public DbSet<PrizeLevel> PrizeLevel { get; set; }
}

Entities/PrizeLevel.cs
namespace MillionaireWeb.Entities;

public class PrizeLevel
{
    public int Id { get; set; }
    public int PrizeAmount { get; set; }
    public bool IsGuaranteed { get; set; } = false;
}

Entities/Question.cs
namespace MillionaireWeb.Entities;

public class Question
{
    public int Id { get; set; }
    public string Content { get; set; }
    public int PrizeLevelId { get; set; }

    public virtual List<Answer> Answers { get; set; }
    public virtual PrizeLevel PrizeLevel { get; set; }
}

Models/AnswerDto.cs
namespace MillionaireWeb.Models;

public class AnswerDto
{
    public int Id { get; set; }
    public string Content { get; set; }
}

Models/CreateQuestionDto.cs
namespace MillionaireWeb.Models;

public class CreateQuestionDto
{
    public int PrizeLevel { get; set; }
    public string Question { get; set; }
    public string CorrectAnswer { get; set; }
    public string WrongAnswer1 { get; set; }
    public string WrongAnswer2 { get; set; }
    public string WrongAnswer3 { get; set; }
}

Models/ErrorViewModel.cs
namespace MillionaireWeb.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/GameViewModel.cs
using MillionaireWeb.Entities;

namespace MillionaireWeb.Models;

public class GameViewModel
{
    public int PrizeLevel { get; set; }
    public int PrizeLevelAmount { get; set; }
    public QuestionDto Question { get; set; }
    public AnswerDto AnswerA { get; set; }
    public AnswerDto AnswerB { get; set; }
    public AnswerDto AnswerC { get; set; }
    public AnswerDto AnswerD { get; set; }

    public int LastAnswerId { get; set; }
    public bool? IsAnswerCorrect { get; set; }
    public bool IsGameWon { get; set; }


    public string CorrectAnswer { get; set; }
    public int QuestionsCount { get; set; }
    public int PreviousPrizeLevelAmount { get; set; }
}

Models/QuestionDto.cs
using MillionaireWeb.Entities;

namespace MillionaireWeb.Models;

public class QuestionDto
{
    public int Id { get; set; }
    public string Content { get; set; }
}

Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using MillionaireWeb.Entities;
using MillionaireWeb.Models;
using MillionaireWeb.Services;

namespace MillionaireWeb.Controllers;
public class GameController : Controller
{
    private readonly IGameService _service;

    public GameController(IGameService service)
    {
        _service = service;
    }

    public IActionResult Index()
    {
        var model = _service.NextGameViewModel(0);
        return View("Index", model);
    }

    [HttpPost]
    public IActionResult Index(GameViewModel model)
    {
        model = _service.ResultGameViewModel(model);
        return View("Index", model);
    }

    [HttpPost]
    public IActionResult Next(int prizeLevel)
    {
        var model = _service.NextGameViewModel(prizeLevel);
        return View("Index", model);
    }

    [HttpPost]
    public IActionResult GameOver(int prizeLevel, bool isResigned)
    {
        int prizeLevelAmount = isResigned
            ? _service.GetPreviousPrizeLevelAmount(prizeLevel)
            : _service.GetPreviousGuaranteedPrizeLevelAmount(prizeLevel);

        return View("GameOver", prizeLevelAmount);
    }

    [HttpPost]
    public IActionResult GameWon()
    {
        int prizeLevelAmount = _service.GetWinningPrizeAmount();
        return View("GameOver", prizeLevelAmount);
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MillionaireWeb.Models;
using System.Diagnostics;

namespace MillionaireWeb.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Mvc;
using MillionaireWeb.Models;
using MillionaireWeb.Services;

namespace MillionaireWeb.Controllers;
public class QuestionsController : Controller
{
    private readonly IQuestionsService _service;

    public QuestionsController(IQuestionsService service)
    {
        _service = service;
    }

    public IActionResult Index()
    {
        int count = _service.GetPrizeLevelCount();
        return View(count);
    }

    [HttpPost]
    public IActionResult Index(CreateQuestionDto dto)
    {
        _service.AddQuestion(dto);
        int count = _service.GetPrizeLevelCount();
        return View(count);
    }
}

Views/Game/GameOver.cshtml
@model int
@{
    ViewData["Title"] = "Game over";
}

<div class="text-center">
    <p class="display-6">You have won</p>
    <p class="display-4">$@Model</p>

    <a asp-controller="Game" asp-action="">
        <button class="btn btn-primary">Play again</button>
    </a>

</div>

Views/Game/Index.cshtml
@model GameViewModel
@{
    ViewData["Title"] = "Game";
}

<div class="text-center">
    <p>Question @Model.PrizeLevel out of @Model.QuestionsCount - You are playing for $@Model.PrizeLevelAmount</p>
    <div class="border border-dark border-2 bg-light rounded m-2">
        <p class="display-6 p-4">@Model.Question.Content</p>
    </div>

    @*
        Before answer is selected it renders this by default
    *@
    @if (Model.IsAnswerCorrect == null)
    {
        @using (Html.BeginForm("Index", "Game", FormMethod.Post))
        {
            <input type="hidden" name="QuestionsCount" value="@Model.QuestionsCount" />
            <input type="hidden" name="PrizeLevel" value="@Model.PrizeLevel" />
            <input type="hidden" name="PrizeLevelAmount" value="@Model.PrizeLevelAmount" />
            <input type="hidden" name="Question.Id" value="@Model.Question.Id" />
            <input type="hidden" name="Question.Content" value="@Model.Question.Content" />
            <input type="hidden" name="AnswerA.Id" value="@Model.AnswerA.Id" />
            <input type="hidden" name="AnswerB.Id" value="@Model.AnswerB.Id" />
            <input type="hidden" name="AnswerC.Id" value="@Model.AnswerC.Id" />
            <input type="hidden" name="AnswerD.Id" value="@Model.AnswerD.Id" />
            <input type="hidden" name="AnswerA.Content" value="@Model.AnswerA.Content" />
            <input type="hidden" name="AnswerB.Content" value="@Model.AnswerB.Content" />
            <input type="hidden" name="AnswerC.Content" value="@Model.AnswerC.Content" />
            <input type="hidden" name="AnswerD.Content" value="@Model.AnswerD.Content" />

            <div class="d-flex flex-column mb-4">
                <button class="btn btn-dark m-2" type="submit" name="LastAnswerId" value="@Model.AnswerA.Id">A. @Model.AnswerA.Content</button>
                <button class="btn btn-dark m-2" type="submit" name="LastAnswerId" value="@Model.AnswerB.Id">B. @Model.AnswerB.Content</button>
                <button class="btn btn-dark m-2" type="submit" name="LastAnswerId" value="@Model.AnswerC.Id">C. @Model.AnswerC.Content</button>
                <button class="btn btn-dark m-2" type="submit" name="LastAnswerId" value="@Model.AnswerD.Id">D. @Model.AnswerD.Content</button>
            </div>
            <hr />
        }
        @using (Html.BeginForm("GameOver", "Game", FormMethod.Post))
        {
            <input type="hidden" name="QuestionsCount" value="@Model.QuestionsCount" />
            <input type="hidden" name="prizeLevel" value="@Model.PrizeLevel" />

            <p>Resign and take $@Model.PreviousPrizeLevelAmount</p>
            <button class="btn btn-primary" type="submit" name="isResigned" value="true">Resign</button>
        }
    }

    @*
        After answer is selected it renders appropriate button
    *@
    @if (Model.IsAnswerCorrect != null)
    {
        <div class="d-flex flex-column">
            <button class="btn btn-dark m-2" disabled>A. @Model.AnswerA.Content</button>
            <button class="btn btn-dark m-2" disabled>B. @Model.AnswerB.Content</button>
            <button class="btn btn-dark m-2" disabled>C. @Model.AnswerC.Content</button>
            <button class="btn btn-dark m-2" disabled>D. @Model.AnswerD.Content</button>
        </div>
        <hr />
        @if (Model.IsAnswerCorrect == true)
        {
            @if(Model.IsGameWon)
            {
                @using (Html.BeginForm("GameWon", "Game", FormMethod.Post))
                {
                    <p>Correct!</p>
                    <button class="btn btn-primary m-2" type="submit" name="prizeLevel" value="@Model.PrizeLevel">Congratulations!</button>
                }
            }
            else
            {
                @using (Html.BeginForm("Next", "Game", FormMethod.Post))
                {
                    <p>Correct!</p>
                    <button class="btn btn-success m-2" type="submit" name="prizeLevel" value="@Model.PrizeLevel">Next Question</button>
                }
            }
        }
        @if (Model.IsAnswerCorrect == false)
        {
            @using (Html.BeginForm("GameOver", "Game", FormMethod.Post))
            {
                <p>Wrong! Correct answer: @Model.CorrectAnswer</p>
                <input type="hidden" name="prizeLevel" value="@Model.PrizeLevel" />
                <button class="btn btn-danger m-2" type="submit" name="isResigned" value="false">Game over</button>
            }
        }
    }
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Who Wants To Be A Millionaire?</h1>
    <p>This is simple game where you answer 14 questions and win money!</p>
    <p>Click button below!</p>
    <a asp-controller="Game" asp-action="">
        <button class="btn btn-primary">Play</button>
    </a>
</div>

Views/Questions/Index.cshtml
@model int
@{
    ViewData["Title"] = "Add question";
}

@using (Html.BeginForm("Index", "Questions", FormMethod.Post))
{
    <div class="d-flex flex-column">
        <div class="row m-2">
            <label class="col-sm-2 col-form-label">Prize level</label>
            <div class="col-sm-10">
                @Html.DropDownList("Prizelevel",
                    Enumerable.Range(1, Model).Select(x => new SelectListItem {
                        Text = x.ToString(),
                        Value = x.ToString()
                    }), new {@class="form-control"})
            </div>
        </div>
        <div class="row m-2">
            <label class="col-sm-2 col-form-label">Question</label>
            <div class="col-sm-10">
                <input class="form-control border-primary" type="text" name="Question" required/>
            </div>
        </div>
        <div class="row m-2">
            <label class="col-sm-2 col-form-label">Correct answer</label>
            <div class="col-sm-10">
                <input class="form-control border-success" type="text" name="CorrectAnswer" required />
            </div>
        </div>
        <div class="row m-2">
            <label class="col-sm-2 col-form-label">WrongAnswer1</label>
            <div class="col-sm-10">
                <input class="form-control border-danger" type="text" name="WrongAnswer1" required />
            </div>
        </div>
        <div class="row m-2">
            <label class="col-sm-2 col-form-label">WrongAnswer2</label>
            <div class="col-sm-10">
                <input class="form-control border-danger" type="text" name="WrongAnswer2" required />
            </div>
        </div>
        <div class="row m-2">
            <label class="col-sm-2 col-form-label">WrongAnswer3</label>
            <div class="col-sm-10">
                <input class="form-control border-danger" type="text" name="WrongAnswer3" required />
            </div>
        </div>
        <div class="row m-2">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <button class="btn btn-primary" type="submit">Add</button>
            </div>
        </div>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MillionaireWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MillionaireWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Millionaire Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Game</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Questions" asp-action="Index">Add question</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MillionaireWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>